# Generated by Django 2.0.13 on 2020-12-28 11:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_list',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Academic'), ('ST', 'Student'), ('SC', 'Scolarship'), ('IN', 'Industry'), ('EM', 'Employment'), ('CV', 'Corona'), ('IT', 'International')], max_length=20),
        ),
    ]
