# Generated by Django 2.0.13 on 2020-12-28 13:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201228_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='subscription_list',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'Academic'), ('ST', 'Student'), ('SC', 'Scolarship'), ('IN', 'Industry'), ('EM', 'Employment'), ('CV', 'Corona'), ('IT', 'International')], max_length=20),
        ),
    ]
