# Generated by Django 2.0.13 on 2020-12-29 15:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201229_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('subscription_list', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'Academic'), ('ST', 'Student'), ('SC', 'Scolarship'), ('IN', 'Industry'), ('EM', 'Employment'), ('CV', 'Corona'), ('IT', 'International')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='notice',
            name='subscribed',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
