# Generated by Django 2.1.15 on 2020-12-30 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201230_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='notice',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed_menu', to=settings.AUTH_USER_MODEL),
        ),
    ]
