# Generated by Django 2.1.15 on 2020-12-30 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notice_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='subscribed',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribed_menu', to=settings.AUTH_USER_MODEL),
        ),
    ]
