# Generated by Django 2.0.13 on 2021-01-02 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201230_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed_menu', to=settings.AUTH_USER_MODEL),
        ),
    ]
